#!/bin/sh

####################################################################
#### Pipeline  3: Preprocessing - SNV calling - VEP annotation ####
####################################################################


### PIPELINE ARGUMENTS 

MDAP=$1
local=$2
run=$3
REF=$4
cvcf=$5
ped=$6
softwarePath=$7
tasksPath=${softwarePath}/tasks




printf "\n..................\n"
printf "  COMBINED GVCFs  \n"
printf "..................\n"

# Combined GVCFs generated by sample into une multi-sample VCF


$tasksPath/combinedGVCF.sh $local $MDAP $run $REF $softwarePath
if [ "$?" != "0" ]  ; then exit 1; fi

	


printf "\n..........................\n"
printf "  GENOTYPING GVCFs  \n"
printf "............................\n"


# Genotyping g.vcf
input=$MDAP/genotyping/${run}.g.vcf
output=$MDAP/genotyping/${run}.vcf
$tasksPath/genotyping.sh $local $run $MDAP $run $input $output $REF $ped $softwarePath
if [ "$?" != "0" ]  ; then exit 1; fi




printf "\n...............\n"
printf "  FILTERING SNVs  \n"
printf "..................\n"


# Filtering SNVs 

ftype="HF"

$tasksPath/SNVfiltering.sh $local $run $MDAP $run $REF $ftype $cvcf $softwarePath
if [ "$?" != "0" ]  ; then exit 1; fi




printf "\n..........................\n"
printf "  GENOTYPE REFINEMENT \n"
printf "............................\n"


		
# Genotype Refinement

$tasksPath/genotypeRefinement.sh $local $run $MDAP $ped $REF $softwarePath
if [ "$?" != "0" ]  ; then exit 1; fi


